import type { Lang } from "./lang";

export type { Lang };

export const COPY = {
  ru: {
    common: {
      lang: "EN",
      back: "Все лаборатории",
      pause: "Пауза",
      resume: "Дальше",
      reset: "Сброс",
      speed: "Скорость",
      theory: "теория",
      trials: "прогонов",
      footnote: "Частоты сходятся к формулам. Не к ощущению.",
    },
    hub: {
      kicker: "Технодемки вероятностей",
      title: "Paradox Labs",
      lead: "Три штуки, которые ломают голову. Не философия — частоты. Симулятор крутится, пока цифра не совпадёт с формулой.",
      open: "Открыть лаб",
      cards: [
        {
          id: "01",
          to: "/monty",
          title: "Монти Холл",
          hook: "Выбрал дверь, ведущий открыл пустую. Теперь 50/50?",
          punch: "Нет. Смена бьёт чаще.",
        },
        {
          id: "02",
          to: "/birthday",
          title: "Дни рождения",
          hook: "23 человека в комнате. Шанс совпадения крошечный?",
          punch: "50.7%.",
        },
        {
          id: "03",
          to: "/bayes",
          title: "Ложноположительный",
          hook: "Тест точный на 99%. Положительный — почти наверняка болен?",
          punch: "При редкой болезни — около 50%.",
        },
      ],
    },
    monty: {
      kicker: "Лаборатория 01",
      title: "Монти Холл",
      lead: "Выбираешь дверь. Ведущий открывает пустую. Остаёшься или меняешь — частота побед не живёт в голове, она вылезает в результатах.",
      stay: "Остаться",
      switch: "Сменить",
      doors: "Комнат",
      hostOpens: "Ведущий открывает пустых",
      last: "Последняя партия",
      pick: "выбор",
      prize: "приз",
      opened: "открыта",
      alt: "смена",
      whyTitle: "Почему процент сдвигается",
      whyBody:
        "Приз никуда не переезжает. Меняется информация: ведущий знает, где пусто, и намеренно открывает козу. Твоя первая дверь по-прежнему 1/n. Вся остальная вероятность схлопывается на неоткрытые чужие двери.",
      formulaStay: "P(остаться) = 1 / n",
      formulaSwitch: "P(сменить) = (1 − 1/n) / (n − 1 − k)",
      formulaHint: "n — комнаты, k — сколько пустых открыл ведущий.",
    },
    birthday: {
      kicker: "Лаборатория 02",
      title: "Парадокс дней рождения",
      lead: "Сколько людей нужно, чтобы двое с днём рождения в один день стали вероятнее орла на монете. Интуиция орёт «сотни». Формула говорит 23.",
      people: "Человек в комнате",
      collision: "Совпадение",
      naive: "Интуиция n/365",
      last: "Последняя комната",
      hit: "совпало",
      miss: "все разные",
      whyTitle: "Почему 23, а не 183",
      whyBody:
        "Считаются не люди, а пары. В 23 человеках уже 253 пары. Каждая пара — маленький шанс, но их много, и уникальность быстро схлопывается.",
      formula: "P = 1 − 365 P n / 365ⁿ",
      formulaHint: "n человек, 365 дней. При n = 23 это ≈ 50.7%.",
    },
    bayes: {
      kicker: "Лаборатория 03",
      title: "Ложноположительный парадокс",
      lead: "Редкая болезнь, точный тест, положительный результат. Мозг ставит точность теста. Байес ставит базу: здоровых больше, ложных плюсов тоже.",
      prev: "Заболеваемость",
      acc: "Точность теста",
      ppv: "P(болен | +)",
      naive: "Интуиция = точность",
      last: "Последние пациенты",
      sick: "болен",
      well: "здоров",
      pos: "+",
      neg: "−",
      tp: "верных +",
      fp: "ложных +",
      whyTitle: "Почему 99% ≠ 99%",
      whyBody:
        "Точность говорит, как тест ведёт себя при известном статусе. Тебе нужно наоборот: статус при известном тесте. Если болеет 1 из 100, а ложный плюс тоже 1 из 100 здоровых — плюсов от здоровых столько же, сколько от больных.",
      formula: "PPV = se·π / (se·π + (1−sp)·(1−π))",
      formulaHint: "π — заболеваемость, se — чувствительность, sp — специфичность.",
    },
  },
  en: {
    common: {
      lang: "RU",
      back: "All labs",
      pause: "Pause",
      resume: "Resume",
      reset: "Reset",
      speed: "Speed",
      theory: "theory",
      trials: "trials",
      footnote: "Rates converge to the formulas. Not to the feeling.",
    },
    hub: {
      kicker: "Probability tech demos",
      title: "Paradox Labs",
      lead: "Three things that break your head. Not philosophy — frequencies. The sim runs until the number matches the formula.",
      open: "Open lab",
      cards: [
        { id: "01", to: "/monty", title: "Monty Hall", hook: "You picked a door, the host opened an empty one. Now 50/50?", punch: "No. Switching wins more." },
        { id: "02", to: "/birthday", title: "Birthdays", hook: "23 people in a room. Tiny chance two share a day?", punch: "50.7%." },
        { id: "03", to: "/bayes", title: "False positive", hook: "99% accurate test. Positive means almost certainly sick?", punch: "If the disease is rare — about 50%." },
      ],
    },
    monty: {
      kicker: "Lab 01",
      title: "Monty Hall",
      lead: "Pick a door. The host opens an empty one. Stay or switch — win rates are not a feeling. They show up in the long run.",
      stay: "Stay",
      switch: "Switch",
      doors: "Rooms",
      hostOpens: "Host opens empty doors",
      last: "Last trial",
      pick: "pick",
      prize: "prize",
      opened: "open",
      alt: "switch",
      whyTitle: "Why the odds move",
      whyBody: "The prize never moves. Your information does: the host knows the empty doors and always opens a goat. Your first pick stays at 1/n. The leftover probability concentrates on the still-closed other doors.",
      formulaStay: "P(stay) = 1 / n",
      formulaSwitch: "P(switch) = (1 − 1/n) / (n − 1 − k)",
      formulaHint: "n is rooms, k is empty ones the host opens.",
    },
    birthday: {
      kicker: "Lab 02",
      title: "Birthday paradox",
      lead: "How many people until two share a birthday more often than a coin comes up heads. Intuition yells hundreds. The formula says 23.",
      people: "People in the room",
      collision: "Shared day",
      naive: "Gut n/365",
      last: "Last room",
      hit: "hit",
      miss: "all unique",
      whyTitle: "Why 23, not 183",
      whyBody: "You are not counting people. You are counting pairs. 23 people make 253 pairs. Each pair is a small chance, but there are many, and uniqueness collapses fast.",
      formula: "P = 1 − 365 P n / 365n",
      formulaHint: "n people, 365 days. At n = 23 this is ~ 50.7%.",
    },
    bayes: {
      kicker: "Lab 03",
      title: "False-positive paradox",
      lead: "Rare disease, accurate test, positive result. The brain quotes the accuracy. Bayes quotes the base rate: healthy people outnumber the sick, so false pluses do too.",
      prev: "Prevalence",
      acc: "Test accuracy",
      ppv: "P(sick | +)",
      naive: "Gut = accuracy",
      last: "Last patients",
      sick: "sick",
      well: "well",
      pos: "+",
      neg: "-",
      tp: "true +",
      fp: "false +",
      whyTitle: "Why 99% != 99%",
      whyBody: "Accuracy is how the test behaves given the status. You need the reverse: the status given the test. If 1 in 100 is sick and 1 in 100 healthy people also pings — pluses from the well equal pluses from the sick.",
      formula: "PPV = se*pi / (se*pi + (1-sp)*(1-pi))",
      formulaHint: "pi is prevalence, se sensitivity, sp specificity.",
    },
  },
} as const satisfies Record<Lang, unknown>;
